### ISSUE TITLE
Leaving Fuzz parameters empty causes build errors

### ISSUE THREAD

**Issue by RedNifre** [awslabs/aws-device-farm-jenkins-plugin#10]
According to the description in the plugin, the Fuzz test parameters "Event Count", "Event Throttle" and "Seed" are optional. If I leave them empty, I get these python-errors in AWS:

stream() takes exactly 3 arguments (2 given)
'NoneType' object has no attribute 'filename'

As a work-around I used the same parameters in jenkins that are suggested when creating a Fuzz test on AWS directly:
Event Count: 6000
Event Throttle: 50
(The Seed can actually be left empty)

Not sure if this is a bug in the jenkins plugin or in AWS device farm itself.

**Comment by vbanthia** [comment]
Happened with me too. 

thanks RedNifre  for the work around.

**Comment by ahawker** [comment]
Sorry for the problems!

This happens to be a problem with Built-in Fuzz Android execution in AWS Device Farm and is not related to the Jenkins plugin.

We are currently working on a fix and hope to have it deployed to our production environment very soon. I will be sure to come back and update this issue once we've done so.

**Comment by ahawker** [comment]
We pushed a fix for this issue late last night. I'm going to close  this issue as resolved, but don't hesitate to re-open it if you once again encounter this bug.
