### ISSUE TITLE
Not selecting a test to run causes a nullpointer exception in AWS device farm.

### ISSUE THREAD

**Issue by RedNifre** [awslabs/aws-device-farm-jenkins-plugin#11]
In the "Choose a test to run" section of the plugin, none of the tests is selected by default. If you forget to select one the build fails in AWS with an unhelpful nullpointer exception.

**Comment by ahawker** [comment]
Michael,

Thanks for reporting this issue.

In the correct case, the plugin should actually validate the selection (or lack there of) and block saving of the AWS Device Farm configuration settings until a test type is selected.

We'll be sure to take a look at this and see if we can correct the problem or at the very least, return a more friendly and descriptive message.

Thanks again and sorry for the issue!

**Comment by anurag1408** [comment]
This issue has been fixed
