### ISSUE TITLE
Trying to upload an IPA file gives an error

### ISSUE THREAD

**Issue by rubenvdb** [awslabs/aws-device-farm-jenkins-plugin#12]
Even though the help command reads "File pattern (local to workspace) where the newly built application (.apk, .ipa) exists.", specifying a path to an IPA-file results in error:

    [AWSDeviceFarm] Using App 'build/Release-iphoneos/*.ipa'
    [AWSDeviceFarm] Unknown app artifact to upload: build/Release-iphoneos/*.ipa

**Comment by ahawker** [comment]
Ruben,

Thanks for reporting the issue and I apologize for the problem. The latest version of the Jenkins plugin was built prior to the release of iOS support on AWS Device Farm, so the functionality is still not yet available.

We are in the process of building a new version of the plugin to target our updated SDK and hope to have the new version in the Jenkins Update Center soon.

Until then, iOS tests can still be executed directly through our SDK or from the AWS Console.

I apologize for the inconvenience and will be sure to update this issue once a new version of the Jenkins plugin is released.

**Comment by anurag1408** [comment]
Hi

IOS support is available in the aws-device-farm plugin and new version(1.5) is released in the Jenkins Update Center.

**Comment by ahawker** [comment]
Closing issue as fixed in version 1.5+. Please re-open if you continue to experience the error on that plugin version or newer.
