### ISSUE TITLE
Configuring Credentials Programmatically 

### ISSUE THREAD

**Issue by jason-riddle** [awslabs/aws-device-farm-jenkins-plugin#21]
I'm trying to configure the Access Key / Secret Key for this plugin. Is there a way to do this programmatically without having to open the browser? A lot of other Jenkins plugins can be configured through groovy scripts, so does something similar exist for this plugin?

**Comment by trentpeterson** [comment]
The easiest way is to use the IAM console as outlined in the readme. You may also be interested in the [IAM CLI](http://docs.aws.amazon.com/cli/latest/reference/iam/create-access-key.html), which does allow for you to programmatically manage access keys. That said, you'll need to have credentials necessary to perform the actions in the first place.

If that doesn't answer your question, can you elaborate on your use case so we can make a better recommendation? Thanks!

**Comment by jason-riddle** [comment]
Let me try to clarify. Given that
- I already have a pair of access keys
- I have created the Jenkins instance with the plugin installed

On the settings page, I want to
- Set the Access Key and Secret Key through scripting
- Avoid having to open a browser

A similar example would be the following (Taken from here https://github.com/blacklabelops/jenkins/blob/master/groovy/setEMailSettings.groovy)

I write a groovy script which will be executed using the <code>jenkins-cli.jar</code>. In the groovy script, I have the following:

```groovy
import jenkins.model.*

def inst = Jenkins.getInstance()
def desc = inst.getDescriptor("hudson.tasks.Mailer")
desc.setSmtpAuth("user", "userpass")
desc.setReplyToAddress("dummy@jenkins.bla")
desc.setSmtpHost("smpt host")
desc.setUseSsl(true)
desc.setSmtpPort("2525")
desc.setCharset("UTF-8")

desc.save()
inst.save()
```

This above snippet is configuring the Mailer plugin for Jenkins, but this allows, you to automate configuring the Device Farm plugin without having to open up a browser, click, and type. Visiting the settings page and manually entering in the credentials might be fine if there is only one Jenkins instance, but what happens if I have 100?

I was hoping something like the following existed.
```groovy
import jenkins.model.*

def inst = Jenkins.getInstance()
def desc = inst.getDescriptor("hudson.tasks.AWSDeviceFarm")
desc.setAKID("Access_Key")
desc.setSKID("Secret_Key")

desc.save()
inst.save()
```
and then the Device Farm plugin is configured.

**Comment by trentpeterson** [comment]
Ah, this is helpful and now I understand. Thanks for the additional info. We'll take a look and update this issue.

**Comment by appwiz** [comment]
@jason-riddle we've added this request to our backlog and will take a look at implementing it in the near future (no ETA that I can provide unfortunately). In the meantime, if you would like to contribute a pull request, we are happy to review it.

**Comment by fgbreel** [comment]
There is an open pull request at https://github.com/jenkinsci/aws-device-farm-plugin/pull/22 to bring CasC support, but seems didn't received much attention too.
