### ISSUE TITLE
unable to select from iOS device pools

### ISSUE THREAD

**Issue by jdiaz5513** [awslabs/aws-device-farm-jenkins-plugin#25]
In the plugin configuration for a build I am able to select among Android device pools but I am not seeing any of the configured iOS device pools show up in the list.

Am I missing something? (Yes, I tried hitting refresh.)

**Comment by appwiz** [comment]
Hi @jdiaz5513, apologies for the late reply. What type of app have you uploaded?

**Comment by jdiaz5513** [comment]
I've uploaded both Android and iOS builds for ad-hoc runs, and have device pools configured for both (our project is cross-platform).

**Comment by appwiz** [comment]
@jdiaz5513, please send me your AWS account ID and project name and I'll take a look the underlying configuration. You can email the information to aws-devicefarm-support@amazon.com referencing this thread.

**Comment by jdiaz5513** [comment]
Done, thanks.

**Comment by appwiz** [comment]
@jdiaz5513, I cloned your device pool into my account and was able to view and use it successfully via Jenkins. As you stated, I had to click "Refresh" for the pool to show up.

* Have you checked if the pool is visible under your project in the [AWS console](https://us-west-2.console.aws.amazon.com/devicefarm/home?region=us-west-2#/projects)? 
* What version of the Jenkins plugin are you using?

**Comment by jdiaz5513** [comment]
I just checked today, it looks like it's working now. Bizarre! It must have been a temporary issue with the API? Thanks for the help, consider this solved.

**Comment by skhanam** [comment]
Hi There,

I have configured like mentioned on the documentation for some reason i see the project being populated on Jenkins however i don't see the device pool.

Could you let me know why its not picking up , when i login to console i see that the device pool is shown.

**Comment by ButkiewiczP** [comment]
Any idea what can be causing this?

I'm also running into this issue despite configuring our Jenkins and IAM user with the necessary policies/keys/etc. The `Project` dropdown correctly displays my projects, but the `Device Pool` dropdown remains empty.

**Comment by nikhil-dabhade** [comment]
@ButkiewiczP : Do you already have a device pool in that project that was created through either console or CLI ? The Jenkins plugin is only going to display pools that were already created through console or CLI.
Also have you tried hitting the refresh button ?

**Comment by ButkiewiczP** [comment]
Yea I've pounded on the refresh button a number of times. There is a device pool attached to that project (2 in fact), but both were created _before_ the Jenkins user, though I don't think that should make a difference. The Jenkins user has the correct IAM policies attached. Does it need any additional permissions besides the deviceFarm permissions?
