### ISSUE TITLE
Enable @Suppress annotation?

### ISSUE THREAD

**Issue by RedNifre** [awslabs/aws-device-farm-jenkins-plugin#35]
Is there a plugin setting to make Device Farm respect the standard Android testrunner @Suppress annotation to exclude tests from being executed? The JUnit 4 annotations work, but we have a large test suite that is mostly JUnit 3.
Does the Jenkins plugin provide a config for this or is @Suppress support missing in Device Farm itself?
If support for that annotation is missing, will it be added or is there a know work-around?

**Comment by appwiz** [comment]
Hi @RedNifre,

The @Suppress annotation is not currently supported. I believe you have an open AWS support case regarding this issue so let's continue the conversation there.
