### ISSUE TITLE
Please add support for Jenkins pipeline

### ISSUE THREAD

**Issue by seaders** [awslabs/aws-device-farm-jenkins-plugin#45]
You have it in some of your other plugins, specifically the publish to S3 one, with this commit the specific containing most of the changes from old style, to the new one,
https://github.com/jenkinsci/s3-plugin/commit/0b4db3ac730702791a67dccbc881a0582cebecb1

**Comment by appwiz** [comment]
Thanks. We will review the pull request.

**Comment by neiljaywarner** [comment]
@seaders  can we have some documentation for this?  the pipeline syntax generator doesn't work when it comes to custom environment for espresso which appears to be required.
