### ISSUE TITLE
Missing option for selecting Appium Version

### ISSUE THREAD

**Issue by andreiaionitoaiesv** [awslabs/aws-device-farm-jenkins-plugin#57]
Hey,

So in the jenkins plugin I don't have any way to select the appium version. I observed that will always run with Appium v .1.4.16 . Any chance to get this done and start Appium with version 1.6.3 ? In the aws console you have this option to select the Appium version

Thanks

**Comment by nikhil-dabhade** [comment]
@andreiaionitoaiesv : Thank you for reaching out to us. We are currently working on deploying an updated version of our Jenkins plugin which will let you chose the Appium version. You can expect this to be in next week.

**Comment by andreiaionitoaiesv** [comment]
Hey @nikhil-dabhade 

Any updates for this issue?

**Comment by nikhil-dabhade** [comment]
@andreiaionitoaiesv : We pushed an update for Jenkins plugin (1.14) which has support for this feature. 

Closing this issue.
