### ISSUE TITLE
1.14 version issues

### ISSUE THREAD

**Issue by mofoAlex** [awslabs/aws-device-farm-jenkins-plugin#62]
Thanks for releasing a new version of the plugin. 
I noticed some issues so far. Idk you guys aware about them, if so just close this ticket.

1. Unable to increase Execution Timeout more than 60 mins.
We bought a more time for our runs and currently we have 150 mins.
![executiontimeout](https://user-images.githubusercontent.com/19596352/27716404-f6c489c8-5cf2-11e7-983e-d7a132912d32.png)

2. Unable to Disable checkboxes on Execution Configuration.
Every time i disabling them, saved, and re-enter the Job configuration they got enabled back by 
themselfs.
![execconfig](https://user-images.githubusercontent.com/19596352/27716581-400722b6-5cf4-11e7-9d59-ca357c8b2c6d.png)

3. Test Filter Field for XCTest UI is not saving a values that was given.
But this problem is mentioned in Issue #53 

Let me know if you need some additional info.

Regards,
Alex.

**Comment by nikhil-dabhade** [comment]
@mofoAlex : Thank you for bringing this to our attention. I am taking a look at these issues and will push a fix soon if I can validate these. Thank you for your patience in this regards.

**Comment by nikhil-dabhade** [comment]
@mofoAlex : The first one is a valid issue. We are working on a fix for it.
For the second issue, we weren't able to reproduce it on multiple instances. Can you share what browser are you using ?

**Comment by mofoAlex** [comment]
@nikhil-dabhade Im using Google Chrome Version 59.0.3071.115 (Official Build) (64-bit) on macSierra 10.12.5. Latest Jenkins update (2.67)

Additional Info:
Also I did update aws-device-farm plugin on top of previews version with saved configuration.
All other checkboxes in the plugin do not have a same issue.

**Comment by nikhil-dabhade** [comment]
@mofoAlex : We released version 1.15 sometime back and these issues were addressed in that release. Please let us know if you are running in any other issues.
