### ISSUE TITLE
Appium 1.6.5 option

### ISSUE THREAD

**Issue by andreiaionitoaiesv** [awslabs/aws-device-farm-jenkins-plugin#64]
Hey,

I noticed that in 1.14 version I don't have the option for Appium 1.6.5. There is a bug in Appium 1.6.3 that blocks me and I cannot run my tests through jenkins. 
There is an issue on WebDriverAgent: 
https://github.com/facebook/WebDriverAgent/issues/575

This issue is fixed in Appium 1.6.5.
Currently I run my tests from the device farm console since there I can select the 1.6.5 version, but this is just a workaround.

Thanks

**Comment by nikhil-dabhade** [comment]
Hi @andreiaionitoaiesv Thank you for reporting this.
We have added support for 1.6.5 in this repository code and the plugin can be built from here to immediately unblock you. We are expecting the official bug fix for Jenkins plugin repo to hit early next week. Thank you for your patience in this regard.

**Comment by aryak93** [comment]
The Appium v1.6.5 option is still not available. Can you please make the fix official. 

Thanks

**Comment by nikhil-dabhade** [comment]
@aryak93 : Did you download the plugin from the Jenkins plugin repo ? This should be in. I will revert back in sometime after confirming this.

**Comment by nikhil-dabhade** [comment]
@aryak93  @andreiaionitoaiesv : I checked and updated the repo with 1.15 which includes few updates too. It should get reflected in 24 hrs on the official plugin repo. Please let us know if you run in to issues thereafter.

**Comment by nikhil-dabhade** [comment]
1.15 is now available with the fixes. 
Please let me know if you having the Appium issue with this version.
