### ISSUE TITLE
support for Appium 1.7.1 ?

### ISSUE THREAD

**Issue by jeffreylail** [awslabs/aws-device-farm-jenkins-plugin#69]
Hey there awslabs!

I noticed in the AWS console, there's an option to use Appium version 1.7.1 (with Appium Python type.)

But I don't have this option in your Jenkins plugin, v1.15.
Any plans to support this? My tests are erroring on Appium version 1.6.5.

Currently I have to run my tests via command line or from the device farm console since in order to select the 1.7.1 version.

Thanks in advance,

**Comment by JianqingSeattle** [comment]
There is a pending pull request for this feature: https://github.com/awslabs/aws-device-farm-jenkins-plugin/pull/66

**Comment by morphysk** [comment]
Can someone merge this? it will be great

**Comment by rvarum** [comment]
i think this options should be free text field or something.
i'm not sure every appium version change should require new plugin build.
AWS device farm now supports up to appium 1.7.2

**Comment by nikhil-dabhade** [comment]
This is now complete.
