### ISSUE TITLE
Upload for web App test always fail when picking the unmetered device

### ISSUE THREAD

**Issue by solariswu** [awslabs/aws-device-farm-jenkins-plugin#75]
AWSDeviceFarmRecorder.java

Two places calling 

if (isRunUnmetered != null && isRunUnmetered) {
                String os = adf.getOs(appArtifact);

public FormValidation doCheckIsRunUnmetered(@QueryParameter Boolean isRunUnmetered, @QueryParameter String appArtifact) {
            if (isRunUnmetered != null && isRunUnmetered) {
                AWSDeviceFarm adf = getAWSDeviceFarm();
                String os = null;
                try {
                    os = adf.getOs(appArtifact);

Without checking whether it's a Web App test which does not have an appArtiffact.
It will always throw following error when testing Web App on an unmetered device.
"            throw new AWSDeviceFarmException(String.format("Unknown app artifact to upload: %s", appArtifact));"

**Comment by anurag1408** [comment]
Hi

This is fixed in the latest release of plugin 1.22
