### ISSUE TITLE
Too many open files problem

### ISSUE THREAD

**Issue by hodaz** [awslabs/aws-device-farm-jenkins-plugin#94]
I am using aws-device-farm plugin in jenkins for UI test.

Whenever the job is executed, open files are growing more and more.

To confirm this issue, I just run "lsof -p [jenkins pid]" on terminal.

The open files are almost report relative results.

I enlarged the limit to 65535 and when it comes to the limit, I should restart jenkins.

Could you tell me how to avoid it or confirm this issue?

**Comment by stefanverhoeff** [comment]
Yep, can confirm the bug since I experienced it as well. And there is a fix but it has not been merged yet, see PR #92

You can clone and build that PR and solve your issue with a custom build.

Or maybe @nikhil-dabhade could have a look at the PR.

**Comment by hodaz** [comment]
I got it. Thank you very much!

**Comment by piyushag-aws** [comment]
@hodaz  Above pull request is merged after testing and new version 1.26 of AWS Device Farm Jenkins plugin is available for use now. Let us know if you still see any issue.
